import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/SmoothScroll";
import { SpeedInsights } from "@vercel/speed-insights/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Muhammad Ali",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
    apple: "/favicon.svg",
  }
};

// i am removing the rendering animation by removring lodingprovider

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <SmoothScroll/>
          {children}
          <SpeedInsights />
      </body>
    </html>
  );
}
